apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deploy
  namespace: spring-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-deploy
    spec:
      containers:
        - name: spring
          image: 730335210712.dkr.ecr.ap-northeast-2.amazonaws.com/kosa-repo:goomong
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: database-url
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: database-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: database-password
            - name: AdminKey
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: admin-key
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mail-username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mail-password
            - name: COS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: cos-key
          resources:
            requests:
              memory: 1Gi
          ports:
            - containerPort: 8080
