apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: spring-boot
data:
  admin-key: OGNkYTU5MzcwMDZlOTU3YjkzZTk2NGNhZjgxNzQyMTA= # 8cda5937006e957b93e964caf8174210
  mail-username: Z29vbW9uZ3Nob3BAZ21haWwuY29t # goomongshop@gmail.com
  mail-password: aW9kbm9xZXV1ZWN1emx5aQ== # iodnoqeuuecuzlyi
  database-url: amRiYzptYXJpYWRiOi8vZGIuZnJlc2gtY2hpY2tlbi5vcmcuaW50ZXJuYWw6MzMwNi9nb29tb25n # jdbc:mariadb://db.fresh-chicken.org.internal:3306/goomong
  database-username: cm9vdA== # root
  database-password: cXdlYXNkenhjIQ== # qweasdzxc!
  cos-key: Y29zMTIzNDUh # cos12345!
